### PR TITLE
Hint reference parsing

### LINKED ISSUE #548: Missing expression in parser
Expressions of the kind `cast(1, felt)` seem to be missing from the parser.

Sample file which can fail: https://github.com/lambdaclass/cairo-vm/blob/main/cairo_programs/bitand_hint.cairo

### PR DESCRIPTION
**Pull request by cicr99**
Fix #548 

The changes in the grammar:
- allow more complex expression to be parsed. For example, more than only two terms to be operated
- include missing cases such as:
    - a simple number as the expression to be casted
    - double dereference inside the expression
- parse the numbers inside the expressions as a string as to allow numbers bigger than 64 bits

### CODE REVIEW

File: pkg/utils/math.go [hunk 1]
```diff
@@ -126,6 +127,32 @@ func FeltDivRem(a, b *fp.Element) (div fp.Element, rem fp.Element) {
...
 }
 
+func Int16FromFelt(n *fp.Element) (int16, bool) {
+	bigN := n.BigInt(new(big.Int))
+	return Int16FromBigInt(bigN)
+}
+
+func Int16FromBigInt(n *big.Int) (int16, bool) {
+	mod := fp.Modulus()
+	negN := new(big.Int).Sub(mod, n)
```
Comment (Sh0g0-1758) [inline pkg/utils/math.go:137]: Can you please explain this implementation. I don't quite understand why you have to take fp_mod - N. suppose that N is bigger than NegN, does that not imply that N is bigger than maxInt16 ?

Comment (cicr99) [reply pkg/utils/math.go:137]: `n` is representing a felt value, so they don't actually have negative numbers, but we know that if `n > P/2 `then we could use the negative value which is `n - P` (`P` in this case is `mod`). As we want to take the int16 value, I'm just trying to obtain the smaller number possible, so you check which one is smaller, n or negN, and then you compare that one to the highest possible value of int16 to check if the number fits in that type. Does it make sense?

File: pkg/hintrunner/zero/hintparser.go [hunk 2]
```diff
@@ -122,80 +148,179 @@ func (expression DerefCastExp) Evaluate() (hinter.Reference, error) {
...
+		}
+		return leftResult, nil
+	} else {
+		for _, term := range expression.AddExp {
+			rightExp, err := term.TermExp.Evaluate()
+			if err != nil {
+				return nil, err
+			}
+
+			op, err := parseOperator(term.Operator)
```
Comment (Sh0g0-1758) [inline pkg/hintrunner/zero/hintparser.go:221]: Can the operator never be "-" here ?

File: pkg/utils/math.go (hunk 1 above)
Comment (Sh0g0-1758) [reply pkg/utils/math.go:137]: Ah yes that makes sense now. Thanks.

**Review by Sh0g0-1758 — APPROVED** [review]
LGTM

File: pkg/hintrunner/zero/hintparser.go [hunk 3]
```diff
@@ -122,80 +148,179 @@ func (expression DerefCastExp) Evaluate() (hinter.Reference, error) {
...
+			return nil, err
+		}
+		return hinter.Immediate(*new(fp.Element).SetBigInt(intExp)), nil
 	case expression.CellRefExp != nil:
 		return expression.CellRefExp.Evaluate()
 	case expression.DerefExp != nil:
 		return expression.DerefExp.Evaluate()
-	case expression.BinOpExp != nil:
-		return expression.BinOpExp.Evaluate()
+	case expression.DDerefExp != nil:
```
Comment (MaksymMalicki) [inline pkg/hintrunner/zero/hintparser.go:288]: I don't quite understand, why could we replace parsing Binary operator with double deref here?

**Review by MaksymMalicki — APPROVED** [review]

File: pkg/hintrunner/zero/hintparser.go (hunk 3 above)
Comment (cicr99) [reply pkg/hintrunner/zero/hintparser.go:288]: So it's not exactly that one is being replaced by the other, the entire grammar changed, so now the Expression type takes the "atomic" expressions of operanders: Immediate, CellRef, Deref and DoubleDeref. For BinOp, notice that with this grammar we can now have several terms in a sumation instead of only 2, so we introduced the type ArithmeticExpression in the grammar, which can be evaluated into Binary Operations. Also, for allowing multiple terms, now the left and right hand side of the binary operation are resOperanders, which allows the structure to be recursive.
For example, the expression: `"cast([ap + 3] + [ap + (-4)] * 18 + 15, felt)"` would be evaluated as:
```
hinter.BinaryOp{
    Operator: hinter.Add,
    Lhs: hinter.BinaryOp{
        Operator: hinter.Add,
        Lhs:      hinter.Deref{
             Deref: hinter.ApCellRef(3),
        },
        Rhs: hinter.BinaryOp{
             Operator: hinter.Mul,
             Lhs: hinter.Deref{
                  Deref: hinter.ApCellRef(-4),
             },
            Rhs: hinter.Immediate(18),
        },
    },
    Rhs: hinter.Immediate(15),
}
```
